# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'maintable.ui'
#
# Created: Sun Jul 21 17:42:03 2013
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainTable(object):
    def setupUi(self, MainTable):
        MainTable.setObjectName(_fromUtf8("MainTable"))
        MainTable.resize(720, 519)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Recursos/i160x130.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainTable.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(MainTable)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 531, 431))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.tablero = QtGui.QGridLayout(self.gridLayoutWidget)
        self.tablero.setSpacing(1)
        self.tablero.setMargin(0)
        self.tablero.setObjectName(_fromUtf8("tablero"))
        self.cmdVerificar = QtGui.QPushButton(self.centralWidget)
        self.cmdVerificar.setGeometry(QtCore.QRect(640, 350, 71, 27))
        self.cmdVerificar.setObjectName(_fromUtf8("cmdVerificar"))
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(560, 130, 67, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lbl_jugador = QtGui.QLabel(self.centralWidget)
        self.lbl_jugador.setGeometry(QtCore.QRect(560, 150, 151, 20))
        self.lbl_jugador.setText(_fromUtf8(""))
        self.lbl_jugador.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_jugador.setObjectName(_fromUtf8("lbl_jugador"))
        self.crono = QtGui.QLCDNumber(self.centralWidget)
        self.crono.setGeometry(QtCore.QRect(560, 390, 151, 51))
        self.crono.setSegmentStyle(QtGui.QLCDNumber.Filled)
        self.crono.setProperty("intValue", 0)
        self.crono.setObjectName(_fromUtf8("crono"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(560, 180, 67, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.lbl_level = QtGui.QLabel(self.centralWidget)
        self.lbl_level.setGeometry(QtCore.QRect(560, 200, 151, 20))
        self.lbl_level.setText(_fromUtf8(""))
        self.lbl_level.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_level.setObjectName(_fromUtf8("lbl_level"))
        self.lbl_icon = QtGui.QLabel(self.centralWidget)
        self.lbl_icon.setGeometry(QtCore.QRect(570, 10, 131, 111))
        self.lbl_icon.setFrameShape(QtGui.QFrame.Box)
        self.lbl_icon.setFrameShadow(QtGui.QFrame.Raised)
        self.lbl_icon.setText(_fromUtf8(""))
        self.lbl_icon.setPixmap(QtGui.QPixmap(_fromUtf8(":/Recursos/i160x130.png")))
        self.lbl_icon.setScaledContents(True)
        self.lbl_icon.setObjectName(_fromUtf8("lbl_icon"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.centralWidget)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(560, 230, 151, 111))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.tecladoNum = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.tecladoNum.setMargin(0)
        self.tecladoNum.setObjectName(_fromUtf8("tecladoNum"))
        self.cmdHint = QtGui.QPushButton(self.centralWidget)
        self.cmdHint.setGeometry(QtCore.QRect(560, 350, 71, 27))
        self.cmdHint.setObjectName(_fromUtf8("cmdHint"))
        MainTable.setCentralWidget(self.centralWidget)
        self.Menu = QtGui.QMenuBar(MainTable)
        self.Menu.setGeometry(QtCore.QRect(0, 0, 720, 25))
        self.Menu.setObjectName(_fromUtf8("Menu"))
        self.menuPartida = QtGui.QMenu(self.Menu)
        self.menuPartida.setObjectName(_fromUtf8("menuPartida"))
        self.menuAcerca_de = QtGui.QMenu(self.Menu)
        self.menuAcerca_de.setObjectName(_fromUtf8("menuAcerca_de"))
        MainTable.setMenuBar(self.Menu)
        self.mainToolBar = QtGui.QToolBar(MainTable)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainTable.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainTable)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainTable.setStatusBar(self.statusBar)
        self.actionCargar = QtGui.QAction(MainTable)
        self.actionCargar.setObjectName(_fromUtf8("actionCargar"))
        self.actionGuardar = QtGui.QAction(MainTable)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionSalir = QtGui.QAction(MainTable)
        self.actionSalir.setObjectName(_fromUtf8("actionSalir"))
        self.actionNueva = QtGui.QAction(MainTable)
        self.actionNueva.setObjectName(_fromUtf8("actionNueva"))
        self.actionRanking = QtGui.QAction(MainTable)
        self.actionRanking.setObjectName(_fromUtf8("actionRanking"))
        self.actionAcerca_de = QtGui.QAction(MainTable)
        self.actionAcerca_de.setObjectName(_fromUtf8("actionAcerca_de"))
        self.menuPartida.addAction(self.actionNueva)
        self.menuPartida.addSeparator()
        self.menuPartida.addAction(self.actionCargar)
        self.menuPartida.addAction(self.actionGuardar)
        self.menuPartida.addSeparator()
        self.menuPartida.addAction(self.actionSalir)
        self.menuAcerca_de.addAction(self.actionRanking)
        self.menuAcerca_de.addSeparator()
        self.menuAcerca_de.addAction(self.actionAcerca_de)
        self.Menu.addAction(self.menuPartida.menuAction())
        self.Menu.addAction(self.menuAcerca_de.menuAction())

        self.retranslateUi(MainTable)
        QtCore.QMetaObject.connectSlotsByName(MainTable)

    def retranslateUi(self, MainTable):
        MainTable.setWindowTitle(QtGui.QApplication.translate("MainTable", "QSudoku 0.2.05", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdVerificar.setText(QtGui.QApplication.translate("MainTable", "Verificar", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainTable", "Jugador:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainTable", "Nivel:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdHint.setText(QtGui.QApplication.translate("MainTable", "Hints(0)", None, QtGui.QApplication.UnicodeUTF8))
        self.menuPartida.setTitle(QtGui.QApplication.translate("MainTable", "Partida", None, QtGui.QApplication.UnicodeUTF8))
        self.menuAcerca_de.setTitle(QtGui.QApplication.translate("MainTable", "Ajustes", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCargar.setText(QtGui.QApplication.translate("MainTable", "Cargar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionCargar.setShortcut(QtGui.QApplication.translate("MainTable", "Ctrl+C", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setText(QtGui.QApplication.translate("MainTable", "Guardar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionGuardar.setShortcut(QtGui.QApplication.translate("MainTable", "Ctrl+G", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSalir.setText(QtGui.QApplication.translate("MainTable", "Salir", None, QtGui.QApplication.UnicodeUTF8))
        self.actionNueva.setText(QtGui.QApplication.translate("MainTable", "Nueva", None, QtGui.QApplication.UnicodeUTF8))
        self.actionRanking.setText(QtGui.QApplication.translate("MainTable", "Ranking", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAcerca_de.setText(QtGui.QApplication.translate("MainTable", "Acerca de", None, QtGui.QApplication.UnicodeUTF8))

import images
